### ISSUE TITLE
Week 03 Day 4 - Tic Tac Toe

### ISSUE THREAD

**Issue by gstark** [KarstenRogers/Assignments#11]
With a partner, create a design for a tic-tac-toe game. Practice your technical design skills (i.e. thinking about _how_ you would code this).

## Objectives

- Plan and design "ideas"
- Collaborate and communicate effectively around technical ideas
- Implement code together with a partner

## Requirements

Features to consider:

- [x] Game should be played on the same computer.
- [x] As a user, I should be able to see a tic-tac-toe board.
- [x] As a user, the game should alternate turns, between `X` and `O`.
- [x] As a user, I should be able to click in a square and play either `X` or `O`, respective of the turn.
- [x] As a user, when I get three in a row, I should be told I've won and the game should be over.

**TIPS:**

- These designs should be so detailed that you could give them another team and they could implement it with few (if any) questions.
- If at any time you want to validate a piece of your design (e.g. the algorithm, event handling, or UI/UX), you can create an _extremely simple_ site that proves or disproves your idea.

### Explorer Mode

WITH your partner: submit a full design of how to approach this problem. This should include:

- [ ] A digital mock up (created using software, or a photo/scan of an analog drawing)
- [ ] Implementation details, such as how you are implementing each square
- [ ] A list of events you are listening for
- [ ] _psuedo-code_ describing your program (e.g. event-handling, game logic)

Finally, also with your partner:
- [ ] Create your tic-tac-toe game!

### Adventure Mode

- [ ] Plan the implementation of a "vs computer" mode, that picks a random square.

_or_

- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable.

### Epic Mode

- [ ] Modify your "vs computer" mode to follow a specific strategy (of your choice).

## Additional Resources

- [PEDAC](https://medium.com/launch-school/solving-coding-problems-with-pedac-29141331f93f)
- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.
- Read about [Pseudocode](https://en.wikipedia.org/wiki/Pseudocode)

**Comment by KarstenRogers** [comment]
ttt-gabeo14.surge.sh 
https://github.com/gabeo14/ttt

**Comment by gstark** [comment]
Very nice!

**Comment by gstark** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/LVd5Cs8l9QSScbnOn2/200w_d.gif)
