### ISSUE TITLE
Week 06 Day 2 - A Sound Board with Sass

### ISSUE THREAD

**Issue by ambethia** [KarstenRogers/Assignments#21]
In this assignment, you'll start with a partially complete Sound Board application and make it your own.

## Objectives

- Use features of Sass to style an application
- Practice React

## Requirements

Starting from the [implementation we created in class](https://github.com/suncoast-devs/cohort-xi/tree/master/week-06/day-2/sound-board), create your own Sound Board application.

Note the addition of `node-sass` to the project's dependencies.

### Explorer Mode

- [x] Have at least 3 sound boards defined in `library.js`, with at least 4 sounds each.
- [x] Use Sass for your CSS, explore and use the following features:
  - [x] Variable
  - [x] Nesting
  - [x] [Functions](https://sass-lang.com/documentation/Sass/Script/Functions.html)

### Adventure Mode

- [ ] Use these Sass features
  - [ ] Mixins
  - [ ] Inheritance
  - [ ] Break your styles into multiple files using `@import`

### Epic Mode

- [ ] Create a "Video Clip" board, that plays different video clips when thumbnails are clicked.

## Additional Resources

- https://sass-lang.com/guide

**Comment by KarstenRogers** [comment]
https://github.com/KarstenRogers/soundboard

soundboardkarsten.surge.sh

**Comment by ambethia** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
