### ISSUE TITLE
Week 07 Day 2 - Intro to Phaser Games

### ISSUE THREAD

**Issue by gstark** [KarstenRogers/Assignments#24]
## Using a Front End Gaming Library

In this assignment, you'll build a simple game

## Objectives

- Learn a new front end library
- Experiment with writing games

### Explorer Mode

- [x] Get the demo we did in class working locally.
- [x] Play with changing the physics settings in the game to adjust the game play.
- [x] Update the images to your own style.
- [x] Add a new feature to, or change an existing feature of, the game

### Adventure Mode

- [ ] Modify your game to a new game, or create your own!

**Comment by KarstenRogers** [comment]
done might go back and do some styling to it 

https://github.com/KarstenRogers/first-phaser-app

**Comment by KarstenRogers** [comment]
first-phaser-app-gstark.surge.sh

**Comment by gstark** [comment]
Fun!!

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
