### ISSUE TITLE
Week 07 Day 4 - Wireframes

### ISSUE THREAD

**Issue by gstark** [KarstenRogers/Assignments#26]
## Build wireframes of your Capstone Project

# Be prepared to show these to your instructor early next week.

**Comment by KarstenRogers** [comment]
![screen shot 2018-11-13 at 7 46 41 am](https://user-images.githubusercontent.com/42678790/48414338-671d3980-e718-11e8-8528-b0db7897bf89.png)
![screen shot 2018-11-13 at 7 46 57 am](https://user-images.githubusercontent.com/42678790/48414340-68e6fd00-e718-11e8-8e0c-5d13d4f6fe7f.png)
![screen shot 2018-11-13 at 7 47 09 am](https://user-images.githubusercontent.com/42678790/48414342-6ab0c080-e718-11e8-9744-e5bd4b0d1b35.png)

**Comment by ambethia** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bceeb145d881263a0f2f05f92594ddf64d6d8c0a/giphy-13.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/78)**__
